INSERT INTO product (category,code,description,name,price) VALUES ('ACESSORIO', '1004', 'Carteira Vermelho', 'Carteira Feminina Vermelho', 35.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('ACESSORIO', '1005', 'Carteira Branco', 'Carteira Feminina Branco', 30.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('ACESSORIO', '1006', 'Cinto Amarelo', 'Cinto Feminino Amarelo', 49.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('ACESSORIO', '1007', 'Cinto Vermelho', 'Cinto Feminino Vermelho', 49.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('CALCADO', '2004', 'Salto Preto', 'Salto Feminino Preto', 109.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('CALCADO', '2005', 'Salto Marrom', 'Salto Feminino Marrom', 99.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('CALCADO', '2006', 'Sandalia de Couro Preto', 'Sandalia de Couro Feminino Preto', 59.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('CALCADO', '2007', 'Sandalia de Couro Marrom', 'Sandalia de Couro Feminino Marrom', 49.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('VESTUARIO', '3006', 'Calça Social Roxo', 'Calça Social Feminino Roxo', 219.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('VESTUARIO', '3007', 'Calça Social Rosa', 'Calça Social Feminino Rosa', 209.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('VESTUARIO', '3008', 'Camisa Social Roxo', 'Camisa Social Feminino Roxo', 159.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('VESTUARIO', '3009', 'Camisa Social Listrada', 'Camisa Social Feminino Listrada', 129.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('VESTUARIO', '3010', 'Camisa Social Rosa', 'Camisa Social Feminino Rosa', 159.00
INSERT INTO product (category,code,description,name,price) VALUES ('VESTUARIO', '3011', 'Camisa Social Salmão', 'Camisa Social Feminino Salmão', 129.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('ACESSORIO', '1013', 'Carteira Cinza', 'Carteira Feminina Branco', 34.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('ACESSORIO', '1014', 'Cinto Xadrex', 'Cinto Feminino Amarelo', 49.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('CALCADO', '2012', 'Salto Bege', 'Salto Feminino Preto', 49.00);'
INSERT INTO product (category,code,description,name,price) VALUES ('CALCADO', '2013', 'Salto Colorido', 'Salto Feminino Marrom', 49.00);'