apiVersion: apps/v1
kind: Deployment
metadata:
  name: api--product-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: api--product
  template: 
    metadata:
        name: api--product
        labels:
          app: api--product
    spec:
        containers:
          - name: api--product-container
            image: $dck-accountid/$dck-repository:api--product-$githash
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "dev"
              - name: CONFIG_SERVER
                value: "http://svc-server--config-service.shoes-eks.svc.cluster.local:8888/config/"
              - name: LOGIN_URL
                value: "http://svc-login.ns-login.svc.cluster.local:7080"
              - name: MYSQL_HOST
                value: "mysql.ns-infra.svc.cluster.local"
              - name: DISCOVERY_HOST
                value: "http://svc-server--discovery-stack.shoes-eks.svc.cluster.local:8762"
            ports:
              - containerPort: 5000
              - containerPort: 9090
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
